### ISSUE TITLE
Error: West US 2 RegionDoesNotAllowProvisioning (SQL)

### ISSUE THREAD

**Issue by hfleitas** [tayganr/purviewlab#47]
Pls replace the region in the template with another region in the One-Click template that doesn't have the restriction to smoothen the deployment.

**Comment by tayganr** [comment]
Hi @hfleitas, the region is determined based on the resource group chosen during the deployment of the template.
- If you are creating a **new resource group** during the template deployment, you are free to select any region.
- If you are selecting to deploy the lab environment to an **existing resource group**, it will be tied to the location that pre-existing resource group has already been deployed to (i.e. unable to change).

**Comment by superlatch** [comment]
I hit this issue today 'RegionDoesNotAllowProvisioning' when trying to deploy the lab - I've tried both WE and NE regions which failed for both Synapse and SQL instances.  I've had to create a support ticket (sev c) which will probably take a couple of days.   I've not previously encountered this so curious why we now have region restrictions at the subscription level.   I'll keep you posted.
