### ISSUE TITLE
Error: Keyvault already exists.

### ISSUE THREAD

**Issue by hfleitas** [tayganr/purviewlab#48]
Not sure if its luck, but I think we should have more unique logic in the name vs just pvlab...

**Comment by tayganr** [comment]
Hi @hfleitas , the [template](https://github.com/tayganr/purviewlab/blob/main/template/azuredeploy.bicep) generates a random string using the Azure Bicep [guid function](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-string#guid) with the resource group name as an input. This random string is then used as part of the prefix for the deployed resources. For example, **pvlab-{randomString}-keyvault**.

Note: If you are deploying to the same resource group more than once, the guid function will generate the same random string. This is generally not an issue if the pre-existing resources have been deleted, but in the case of Azure Key Vault, it will typically perform a "soft delete" which then causes a conflict of "VaultAlreadyExists" when the template attempts to deploy a second time.

To solve this issue, you can either deploy to a new resource group OR purge the soft-deleted key vault. See these instructions on [how to purge a soft-deleted key vault](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-recovery?tabs=azure-portal#list-recover-or-purge-a-soft-deleted-key-vault).
